### ISSUE TITLE
[Question] Is this kind of modification a pull request? Another plugin?

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/ddu-source-file_rec#1]
Changed the full path to the path from the current directory.
Changed to display only files.
Should the above modifications be pulled? Or should it be treated as a separate plug-in?
![スクリーンショット 2022-01-23 21 20 45](https://user-images.githubusercontent.com/3197942/150678238-821facbd-a27e-45cc-93b0-9284fa05bea9.png)

**Comment by Shougo** [comment]
It should be another converter like this.

https://github.com/Shougo/denite.nvim/blob/master/rplugin/python3/denite/filter/converter/relative_word.py

Because it should not be for file_rec source.

**Comment by nabezokodaikon** [comment]
So that's it. understand.

**Comment by nabezokodaikon** [comment]
Is it possible to make a converter plugin now?

**Comment by Shougo** [comment]
word is changed to relative path like denite.nvim.

**Comment by Shougo** [comment]
And directory items are ignored

**Comment by nabezokodaikon** [comment]
Understand. thank you.
